/*
 Generated by typeshare 1.2.0
*/

/** Represents the core config, contains critical info needed by the core API */
export interface Config {
    owmlPath: string;
    databaseUrl: string;
    alertUrl: string;
    viewedAlerts: string[];
}

/** Represents a mod in the remote database */
export interface RemoteMod {
    downloadUrl: string;
    downloadCount: number;
    version: string;
    name: string;
    uniqueName: string;
    description: string;
    readme?: ModReadMe;
    slug: string;
    required?: boolean;
    repo: string;
    author: string;
    authorDisplay?: string;
    parent?: string;
    prerelease?: ModPrerelease;
    alpha?: boolean;
    tags?: string[];
}

/** A prerelease for a mod */
export interface ModPrerelease {
    downloadUrl: string;
    version: string;
}

/** Contains URLs for a mod's README */
export interface ModReadMe {
    htmlUrl: string;
    downloadUrl: string;
}

/** Represents an installed mod */
export interface LocalMod {
    enabled: boolean;
    errors: ModValidationError[];
    mod_path: string;
    manifest: ModManifest;
}

/** Represents a mod that completely failed to load */
export interface FailedMod {
    error: ModValidationError;
    mod_path: string;
}

/** Represents a manifest file for a local mod. */
export interface ModManifest {
    uniqueName: string;
    name: string;
    author: string;
    version: string;
    filename?: string;
    owmlVersion?: string;
    dependencies?: string[];
    conflicts?: string[];
    pathsToPreserve?: string[];
    warning?: ModWarning;
}

/** Represents a warning a mod wants to show to the user on start */
export interface ModWarning {
    title: string;
    body: string;
}

/** Represents the configuration for OWML */
export interface OWMLConfig {
    gamePath: string;
    debugMode: boolean;
    forceExe: boolean;
    incrementalGC: boolean;
    owmlPath?: string;
    socketPort: number;
}

/** Represents a message sent from the game */
export interface SocketMessage {
    senderName?: string;
    senderType?: string;
    message: string;
    messageType: SocketMessageType;
}

export interface GameMessage {
    port: LogPort;
    message: SocketMessage;
}

export interface GuiConfig {
    theme: Theme;
    rainbow: boolean;
    language: Language;
    watchFs: boolean;
    noWarning: boolean;
}

export interface LogPayload {
    logType: Level;
    target: string;
    message: string;
}

/** Represents the type of message sent from the game */
export enum SocketMessageType {
    Message = "message",
    Error = "error",
    Warning = "warning",
    Info = "info",
    Success = "success",
    Quit = "quit",
    Fatal = "fatal",
    Debug = "debug"
}

/** Represents an error with a [LocalMod] */
export type ModValidationError =
    /** The mod's manifest was invalid, contains the error encountered when loading it */
    | { errorType: "InvalidManifest"; payload: string }
    /** The mod is missing a dependency that needs to be installed, contains the unique name of the missing dep */
    | { errorType: "MissingDep"; payload: string }
    /** A dependency of the mod is disabled, contains the unique name of the disabled dep */
    | { errorType: "DisabledDep"; payload: string }
    /** There's another enabled mod that conflicts with this one, contains the conflicting mod */
    | { errorType: "ConflictingMod"; payload: string }
    /** The DLL the mod specifies in its `manifest.json` doesn't exist, contains the path (if even present) to the DLL specified by the mod */
    | { errorType: "MissingDLL"; payload?: string }
    /** There's another mod already in the DB with this mod's unique name, contains the path of the other mod that has the same unique name */
    | { errorType: "DuplicateMod"; payload: string };

export enum Theme {
    White = "White",
    Blue = "Blue",
    Green = "Green",
    Pink = "Pink",
    Purple = "Purple",
    Yellow = "Yellow",
    Orange = "Orange",
    Blurple = "Blurple",
    GhostlyGreen = "GhostlyGreen"
}

export enum Language {
    English = "English",
    Wario = "Wario"
}
