env:
    browser: true
    es2021: true
settings:
    react:
        version: "detect"
extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:react/jsx-runtime
    # - plugin:react-hooks/recommended
    - plugin:@typescript-eslint/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - react
    - "@typescript-eslint"
rules:
    "react/display-name": off
    "@typescript-eslint/no-non-null-assertion": off
    "@typescript-eslint/no-explicit-any": off
