name: Continuous Integration (Rust)

on:
  push:
    paths:
      - .github/workflows/ci_rs.yml
      - owmods_gui/backend/**
      - owmods_{cli,core}/src/**
      - owmods_{cli,core}/Cargo.toml
      - ./Cargo.toml
      - ./Cargo.lock
    branches:
      - main
      - renovate/{cli,gui,core}
  pull_request:
    paths:
      - .github/workflows/ci_rs.yml
      - owmods_gui/backend/**
      - owmods_cli/**
      - owmods_core/**
      - ./Cargo.toml
      - ./Cargo.lock
    branches:
      - main
      - dev

jobs:
  rs:
    name: Check Rust
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev librsvg2-dev

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Check Formatting
        run: cargo fmt --check

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: v1-check-${{ matrix.platform }}-${{ matrix.target }}-rust-cache-${{ hashFiles('Cargo.lock') }}

      - name: Make Stub Dist Dir
        run: mkdir owmods_gui/dist

      - name: Check Clippy
        run: cargo lint

      - name: Run Tests (Core)
        run: cargo test -p owmods_core
